travis:
  secure:
    BINSTAR_TOKEN: ViAnUxQHBhxvf61j0nBmAO80dVS4TP3kMRgzPEhQxWbgReLV49P/nw3uUvE2Gp1AO51fYghdVyTBZ2tXShFPNvEoLckSV4FaGO4uDouBkOYbVFdWnzoty6FX49zAE0WwGDii/SyVjWocVoNf2o7A9p8h71vqQBWKRg7LAVeXn31Q3F9hhv/rVJAv3p4Yqug60ps2om5WDIfjK0pD0iqAm/prEeRiAqHkVK3kXQ0Th0PY48ikXeC+6kVEJ4QHLLYp/Z5WSHqHLH7GPBlWDUf65XZVAcHEhJwG6fA2Vf4VGle3IHI32za21dDBdad4JI2LzHlmWJfskIU7cy6XcE5Qv0pcT4m+FdmCRM8/G16XwwpMw4iHMNBje+r+Yaavw3ggVDx3ENaAsEZpJk27/sxew0Ajel+KNqWcwkbp+f3s76uixRE2DZhO0m/iV+0Z+V+cEdKabhMbxhTJZuRUYNNpgE5+LcmMMdnEt3/71qNSVNYjt6BK1scp1VugD0zeEWdzCflSXtfBWzi1imEl+r0tKzLDGxkqPYLd+ZRrAMRNXPo/2sH4GWRDB3x6Qxc7C69pZ1+UWxNNjNqzeW6G6tOYvblXFIZ+VQ4UG3xPA+q8cHJqFxZ+HGXLWG0RFi0ZHaGsKY59iLEpu6GUP9MtyxVAQMVTMhY5WyIZopQRdY4Tj6E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
