travis:
  secure:
    BINSTAR_TOKEN: nU2ZN1CoccLOrKvwP0p16aqUtNAMUkQeCpMk1pHc8RJEvciwdHPQRkmc9fLMtibiecN5KeHB0D78KYD3MyVwSkHYD2bUh8TPk5iR9Gtzc/gLnBqz3V0pSvz0Kpoz0LqbglO8VoI4CznSNzTNPSMmtYXjW2pJECOvHZEaXiIAu76fAPYIdibuUJlfUTUs/uttiL1AstTb5zUPrzsuLYhfO0Tm85Q7k7Cbv9sJZzp02Ox6vXjOaysznFmB53v1I3CbLit/5Z0upuY2plr/BFmANAVTDgkAmlpTTfxADmqZ3YaJpR8QfjANYSauUSacRcUYI5/3LszqXaYkHeNo5+viJCXy/PLJpZ+Wxu9Jgf1krTOEDKM5l+aAlWmyomsDBX5YUNltIeclhu38XNlXjTtfI4FR03odrOPhgcF+oZlmvUoLqd674IR4jzxSEnqVqzuk7fmnKHllMhM2KIrNXRu1tpxYOKtI3RaIKMHasW4qO6u1xJDevJ9Gqbovzhw+Wcc6tK8wg9VTwyvLAUfXoyvupOVgWHvr6Bie6cUAYifIkT+hkWlWJmr/bIUdAfYYkXxBtFaWOIIjM6mWGzcu311j9DzxgIW5d4yX1obePt2s4H8dIBcPzVVy/d4VE4T9svAdUhcwxOBgRG7MMLWQBaotmt9JrjofAPdK6ZFKlDbyY8Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
